// SPDX-FileCopyrightText: 2023 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	"sigs.k8s.io/controller-runtime/pkg/conversion"
)

// ConvertTo converts this Resource to the hub type.
func (tr *Resource) ConvertTo(dstRaw conversion.Hub) error {
	return nil
}

// ConvertFrom converts from the hub type to the Resource type.
func (tr *Resource) ConvertFrom(srcRaw conversion.Hub) error {
	return nil
}
